apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: webapp-destination
spec:
  host: webservice
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 2
        connectTimeout: 30ms
        tcpKeepalive:
          time: 7200s
          interval: 75s
      http:
        http2MaxRequests: 4
        maxRequestsPerConnection: 2
    outlierDetection:
      consecutiveGatewayErrors: 2
      consecutive5xxErrors: 2
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100  
  subsets:
  - name: v0
    labels:
      version: "3.0"
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 10
          connectTimeout: 60ms
  - name: v1
    labels:
      version: "3.1"
  - name: v2
    labels:
      version: "3.2"

